export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_END = 'LOGIN_REQUEST_END'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

// For course
export const ADD_COURSE = 'ADD_COURSE'
export const RECEIVE_COURSE = 'RECEIVE_COURSE'
export const REMOVE_COURSE = 'REMOVE_COURSE'
export const CLEAR_COURSE = 'CLEAR_COURSE'
export const LOADING_COURSE = 'LOADING_COURSE'
export const END_LOADING_COURSE = 'END_LOADING_COURSE'
export const COURSE_LOAD_ERROR = 'COURSE_LOAD_ERROR'
export const COURSE_CLEAR_LOAD_ERROR = 'COURSE_CLEAR_LOAD_ERROR'

// For connection
export const CONNECTION_OK = 'CONNECTION_OK'
export const CONNECTION_FAIL = 'CONNECTION_FAIL'
export const CONNECTION_RETRY = 'CONNECTION_RETRY'
export const CONNECTION_WAIT = 'CONNECTION_WAIT'
export const CONNECTION_CONNECTING = 'CONNECTION_CONNECTING'
